package de.cweyermann.ber.ratings.entity;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

import lombok.Data;
import lombok.ToString;

@DynamoDBTable(tableName = "Matches")
@Data
@ToString
public class Match {

    @DynamoDBTyped(DynamoDBAttributeType.S)
    public enum Status
    {
        RATED, DOING, UNRATED
    }
    
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String player1Id;

    private String player2Id;

    private String player3Id;

    private String player4Id;

    private List<EmbeededMatchPlayer> homePlayers;

    private List<EmbeededMatchPlayer> awayPlayers;

    private String league;

    private String hometeam;

    private String awayteam;

    private String discipline;

    private String result;

    private Date date;
    
    private Status processStatus;
    
    private int leagueDepth;

}
